### ISSUE TITLE
0.1.0 beta version release RoadMap

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/octodirect#1]
### :tada: Feature

- [x] 활성화 위치에 따른 스크롤 위치 조정
- [x] redux/redux-saga로 리팩토링
- [x] jest, enzyme으로 test code 작성
- [x] coveralls 붙이기
- [x] 엔터키로 redirect 기능 추가
- [x] GraphQL로 repo 다 받아오기 기능 추가 #5
- [x] localstorage로 permission key(ssh) 등록해서 해당 key로 api 호출하기
- [x] browser history 접근해서 github.com 으로 filtering해서 노출되는 list에 추가
- [x] class style --> `aria-selected` style

### 🎁 Enhancement

- [x] `submit` 시 success alert 띄워주기
- [x] Support custom domain option
- [x] 검색 결과가 없으면 `github:` 을 붙여서 검색시켜주기.
- [x] 로딩이 완료되었을 때, 현재 input value로 filtering 한 번 더하기.
- [x] setting-view UI 변경 (너무 지저분하다.)
- [x] Support guide : `Check, https://github.com/settings/tokens` 대신 issue에 정리하여 링크를 제공
- [x] `submit` 후, main 으로 복귀했을 때, 새로 그리기
- [x] 인증이 필요할 경우, 설정 표시 강조하기

### ♻️ Environment

- [x] `build` 시, drop-console. #10 
- [x] `build` 후, `.zip` 파일 떨구는 script 추가 #10 
- [x] `build` 시, webpack-bundle-analyzer 추가 #10 
- [x] version에 하드 코딩 제거 후, StringReplace로 처리 #10 

### 🐛 Bug fix

- [x] input value 기준으로 filtering 시 대소문자 구분없이 필터하는 것으로 수정.
- [x] Access token 설정 안내 문구 깨짐.
- [x] GitHub API에서 받아지는 값이 없을 때, filtering된 item만 노출되도록 수정.
